[server]
port = 50051

[auth]
internal_token = "internal_token"
jwt_secret = "jwt_secret"
github_client_id = "github_client_id"
github_client_secret = "github_client_secret"
github_redirect_url = "http://localhost:8080/auth/callback"

[session]
expiration_hours = 24

[oauth]
state_expiration_minutes = 10

[redis]
urls = "localhost:6379"

[gorm_client.database]
driver = "postgres"
host = "localhost"
port = 5432
username = "postgres"
password = "postgres"
name = "postgres"
sslmode = "disable"
